// Draft terms of service — placeholder content pending counsel review.
// Wired as a public route (/terms) from App.tsx.
import { Link } from "react-router-dom";
import { AlertTriangle } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="bg-background">
      <div className="container max-w-3xl py-16 md:py-20">
        <div className="flex items-start gap-3 border border-primary/30 bg-primary/10 p-4 text-sm text-primary">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
          <p>
            <strong className="font-semibold">DRAFT — not legal advice, pending counsel review.</strong>{" "}
            This page is a plain-language placeholder describing how the trial works. It has not been
            reviewed by a lawyer and is not a final or binding legal document.
          </p>
        </div>

        <h1 className="mt-10 text-3xl font-extrabold tracking-tight text-foreground">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Draft — last updated {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="mt-10 space-y-10 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="text-lg font-bold text-foreground">The trial</h2>
            <p className="mt-2">
              Tennis AI is currently an early trial for a small group of coaches, players and parents.
              There is no paid plan yet. Features may change, and the trial may be paused or ended at any
              time as we build the product.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">Accounts</h2>
            <p className="mt-2">
              You need an account to use Tennis AI. You're responsible for keeping your login details
              secure and for the accuracy of the information you enter. Accounts for players under 16 are
              expected to be set up and overseen by a parent, guardian or coach.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">Acceptable use</h2>
            <ul className="mt-2 list-disc space-y-1.5 pl-5">
              <li>Only enter data about yourself, or about a player you coach or are the parent/guardian of.</li>
              <li>Don't use the app to harass, impersonate, or misrepresent yourself or others.</li>
              <li>Don't attempt to access accounts or data that aren't yours.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">Your data</h2>
            <p className="mt-2">
              See our <Link to="/privacy" className="text-primary hover:underline">Privacy Policy</Link> for
              what we collect and why. You can ask us to export or delete your data at any time using the
              contact details there.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">No warranty, limited liability</h2>
            <p className="mt-2">
              This is early-stage, trial software provided "as is," without warranties of any kind. Session
              plans, match-prep suggestions and other in-app guidance are generated by rule-based logic, not
              a substitute for professional coaching or medical advice. To the extent permitted by law, we
              are not liable for damages arising from your use of the trial.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">Changes</h2>
            <p className="mt-2">
              We may update these terms as the product and trial evolve. We'll aim to flag material changes
              to trial participants directly.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">Contact</h2>
            <p className="mt-2">
              Questions about this draft can be sent to{" "}
              <a href="mailto:hello@tennisai.example" className="text-primary hover:underline">hello@tennisai.example</a>{" "}
              (placeholder address — to be confirmed).
            </p>
          </section>
        </div>

        <div className="mt-12 flex flex-wrap gap-x-6 gap-y-2 border-t border-border pt-6 text-sm">
          <Link to="/" className="font-medium text-primary hover:underline">Back to home</Link>
          <Link to="/privacy" className="font-medium text-primary hover:underline">Privacy Policy</Link>
        </div>
      </div>
    </div>
  );
}
