// ============================================================
// TennisAI — Session Generator: best-practice drill library
// A curated, level-tagged set of drills grounded in mainstream
// coaching practice (progressive feeding, game-based learning,
// deliberate practice). Each drill carries explicit coaching cues
// (HOW) and a measurable success criterion. Data only — no logic.
// ============================================================

import type { DrillTemplate } from "./types";

export const DRILL_LIBRARY: DrillTemplate[] = [
  // ── Warm-up / activation ───────────────────────────────────────
  {
    id: "wu-dynamic",
    name: "Dynamic movement prep",
    category: "physical",
    focus: ["movement", "fitness"],
    kinds: ["warmup"],
    minLevel: "beginner",
    whatToDo:
      "Two lengths of the court each: jog, high knees, heel-flicks, side-shuffles, walking lunges with rotation, then arm circles and wrist mobility.",
    howToDo: [
      "Raise heart rate gradually — no sprinting yet.",
      "Emphasise range of motion in hips, shoulders and wrists.",
      "Finish with 10 shadow serves to prime the shoulder.",
    ],
    successCriteria: "Player reports feeling loose; no static stretching before hitting.",
    equipment: [],
    suitsGroup: true,
    baseIntensity: "low",
  },
  {
    id: "wu-mini-tennis",
    name: "Mini-tennis (service boxes)",
    category: "technical",
    focus: ["forehand", "backhand", "movement"],
    kinds: ["warmup"],
    minLevel: "beginner",
    whatToDo: "Rally within the service boxes using short, controlled strokes and soft hands.",
    howToDo: [
      "Contact out in front, relaxed grip pressure.",
      "Small split-step before every ball to switch movement on.",
      "Aim for 15+ ball rallies before opening up to full court.",
    ],
    successCriteria: "Sustain a 15-ball cooperative rally without a miss.",
    equipment: ["basket of balls"],
    suitsGroup: true,
    baseIntensity: "low",
  },

  // ── Serve ──────────────────────────────────────────────────────
  {
    id: "sv-targets",
    name: "Serve target zones",
    category: "technical",
    focus: ["serve"],
    kinds: ["technical"],
    minLevel: "beginner",
    whatToDo:
      "Place cones/targets wide, body and T in each box. Serve baskets aiming for the target zones, alternating deuce and ad courts.",
    howToDo: [
      "Consistent toss: release at eye level, ball slightly in front.",
      "Trophy position then drive up to contact — legs load and extend.",
      "Keep the same rhythm on every attempt; reset routine between serves.",
    ],
    successCriteria: "Hit 6 of 10 first serves into the chosen target zone.",
    equipment: ["basket of balls", "target cones"],
    suitsGroup: true,
    baseIntensity: "medium",
  },
  {
    id: "sv-second-kick",
    name: "Second-serve kick under count",
    category: "technical",
    focus: ["serve"],
    kinds: ["technical"],
    minLevel: "intermediate",
    whatToDo: "Hit only second serves (kick/topspin) deep into the box, counting makes in a row.",
    howToDo: [
      "Toss slightly over the head and left; brush low-to-high (7-to-1).",
      "Spin first, pace second — clear the net by a metre.",
      "Full swing — never dink the second serve.",
    ],
    successCriteria: "8 consecutive kick second serves in, landing behind the service line.",
    equipment: ["basket of balls"],
    suitsGroup: false,
    baseIntensity: "medium",
  },

  // ── Return ─────────────────────────────────────────────────────
  {
    id: "rt-depth",
    name: "Return depth targets",
    category: "technical",
    focus: ["return"],
    kinds: ["technical"],
    minLevel: "beginner",
    whatToDo: "Coach/partner serves; returner drives cross-court past a line 2 m inside the baseline.",
    howToDo: [
      "Early split-step timed to the server's contact.",
      "Short backswing, block/drive through the ball.",
      "Recover to centre immediately after contact.",
    ],
    successCriteria: "7 of 10 returns land in the deep target zone.",
    equipment: ["basket of balls", "target line"],
    suitsGroup: true,
    baseIntensity: "medium",
  },

  // ── Forehand ───────────────────────────────────────────────────
  {
    id: "fh-crosscourt",
    name: "Cross-court forehand consistency",
    category: "technical",
    focus: ["forehand"],
    kinds: ["technical"],
    minLevel: "beginner",
    whatToDo: "Live or fed cross-court forehand rally into the deuce-side deep target.",
    howToDo: [
      "Unit turn as the ball leaves the opponent's strings.",
      "Low-to-high swing path, finish over the shoulder.",
      "Aim 1–1.5 m over the net for margin and depth.",
    ],
    successCriteria: "20-ball cross-court rally staying behind the service line.",
    equipment: ["basket of balls", "target cones"],
    suitsGroup: true,
    baseIntensity: "medium",
  },
  {
    id: "fh-inside-out",
    name: "Inside-out forehand pattern",
    category: "tactical",
    focus: ["forehand", "tactics"],
    kinds: ["tactical"],
    minLevel: "intermediate",
    whatToDo:
      "Ball fed to the backhand corner; player runs around it and hits an inside-out forehand to the open court, then recovers.",
    howToDo: [
      "Explosive first step and a wide load on the outside leg.",
      "Hit big cross to the ad-court corner, then reset to centre.",
      "Only run around balls short enough to attack.",
    ],
    successCriteria: "6 of 8 inside-out forehands land in the back third of the ad court.",
    equipment: ["basket of balls"],
    suitsGroup: false,
    baseIntensity: "high",
  },

  // ── Backhand ───────────────────────────────────────────────────
  {
    id: "bh-crosscourt",
    name: "Backhand cross-court depth",
    category: "technical",
    focus: ["backhand"],
    kinds: ["technical"],
    minLevel: "beginner",
    whatToDo: "Cross-court backhand rally targeting a deep zone on the ad side.",
    howToDo: [
      "Early preparation; shoulders turned fully.",
      "Drive through contact, stable non-dominant side.",
      "Keep height and depth — avoid flattening out.",
    ],
    successCriteria: "15-ball cross-court backhand rally without an error.",
    equipment: ["basket of balls", "target cones"],
    suitsGroup: true,
    baseIntensity: "medium",
  },
  {
    id: "bh-dtl-change",
    name: "Backhand down-the-line change of direction",
    category: "tactical",
    focus: ["backhand", "tactics"],
    kinds: ["tactical"],
    minLevel: "intermediate",
    whatToDo: "Rally cross-court, then on the coach's call change direction down the line and finish the point.",
    howToDo: [
      "Change direction on a ball inside the baseline, not on the run.",
      "Contact slightly earlier and out in front to redirect.",
      "Commit — a tentative DTL sits up for the opponent.",
    ],
    successCriteria: "5 of 8 down-the-line changes stay in and pull the opponent wide.",
    equipment: ["basket of balls"],
    suitsGroup: false,
    baseIntensity: "high",
  },
  {
    id: "bh-slice",
    name: "Slice backhand control",
    category: "technical",
    focus: ["backhand"],
    kinds: ["technical"],
    minLevel: "intermediate",
    whatToDo: "Feed a series of low and high balls; player slices deep with control, varying height.",
    howToDo: [
      "High-to-low path, open racquet face, stay down through contact.",
      "Keep the ball low over the net and deep.",
      "Use it to defend and to change rhythm.",
    ],
    successCriteria: "8 of 10 slices land past the service line and stay below net-cord height.",
    equipment: ["basket of balls"],
    suitsGroup: true,
    baseIntensity: "low",
  },

  // ── Net / volley ───────────────────────────────────────────────
  {
    id: "nt-reflex",
    name: "Volley-to-volley reflex",
    category: "technical",
    focus: ["net"],
    kinds: ["technical", "warmup"],
    minLevel: "intermediate",
    whatToDo: "Two players at the net exchange controlled volleys, gradually increasing pace.",
    howToDo: [
      "Racquet up and in front; punch, don't swing.",
      "Split-step on every ball; use the legs, not the wrist.",
      "Watch the ball onto the strings.",
    ],
    successCriteria: "Sustain a 12-ball volley exchange without dropping the racquet head.",
    equipment: ["basket of balls"],
    suitsGroup: true,
    baseIntensity: "medium",
  },
  {
    id: "nt-approach-volley",
    name: "Approach + first volley",
    category: "tactical",
    focus: ["net", "tactics", "movement"],
    kinds: ["tactical"],
    minLevel: "intermediate",
    whatToDo: "Feed a short ball; player hits an approach, closes the net and puts away the first volley.",
    howToDo: [
      "Approach down the line to cut the angle.",
      "Split-step as the opponent contacts, then move forward to the volley.",
      "First volley deep or into open court; then close for the finish.",
    ],
    successCriteria: "6 of 8 approach-and-volley sequences won.",
    equipment: ["basket of balls"],
    suitsGroup: false,
    baseIntensity: "high",
  },

  // ── Movement / footwork ────────────────────────────────────────
  {
    id: "mv-split-first-step",
    name: "Split-step & first-step reaction",
    category: "physical",
    focus: ["movement"],
    kinds: ["warmup", "technical"],
    minLevel: "beginner",
    whatToDo: "Coach points/feeds to a side; player split-steps and explodes two steps to shadow a shot, then recovers.",
    howToDo: [
      "Land the split-step just as the coach signals.",
      "First step is a small adjustment, not a lunge.",
      "Always recover through the centre with cross-steps.",
    ],
    successCriteria: "Consistent split-step timing across 20 reps; sharp recovery each time.",
    equipment: ["cones"],
    suitsGroup: true,
    baseIntensity: "medium",
  },
  {
    id: "mv-wide-recovery",
    name: "Wide-ball defend & recover",
    category: "physical",
    focus: ["movement", "forehand", "backhand"],
    kinds: ["technical", "live"],
    minLevel: "intermediate",
    whatToDo: "Feed alternating wide balls; player hits on the stretch and recovers to centre before the next feed.",
    howToDo: [
      "Load the outside leg; hit high and deep to buy recovery time.",
      "Cross-over or slide (on clay) back to position.",
      "Never stop moving — reset stance before the next ball.",
    ],
    successCriteria: "10 consecutive wide balls returned deep with a full recovery each time.",
    equipment: ["basket of balls", "cones"],
    suitsGroup: false,
    baseIntensity: "high",
  },

  // ── Fitness / conditioning ─────────────────────────────────────
  {
    id: "ft-court-intervals",
    name: "On-court movement intervals",
    category: "physical",
    focus: ["fitness", "movement"],
    kinds: ["technical", "live"],
    minLevel: "beginner",
    whatToDo: "Baseline-to-net-and-back sprints and side-to-side touches: 6 × 30 s work, 30 s rest.",
    howToDo: [
      "Change direction low, off the outside foot.",
      "Full effort in the work block; use the rest fully.",
      "Stop the set if technique/footwork degrades.",
    ],
    successCriteria: "Complete 6 intervals maintaining sprint quality on the last rep.",
    equipment: ["cones", "stopwatch"],
    suitsGroup: true,
    baseIntensity: "high",
  },
  {
    id: "ft-core",
    name: "Core & stability circuit",
    category: "physical",
    focus: ["fitness"],
    kinds: ["cooldown", "technical"],
    minLevel: "beginner",
    whatToDo: "Plank, side-plank, glute bridge, dead-bug — 2 rounds, 30–40 s each.",
    howToDo: [
      "Neutral spine; brace the core, don't hold the breath.",
      "Quality over duration — stop when form breaks.",
    ],
    successCriteria: "2 full rounds with controlled form.",
    equipment: ["mat"],
    suitsGroup: true,
    baseIntensity: "low",
  },

  // ── Tactics / patterns ─────────────────────────────────────────
  {
    id: "tc-serve-plus-one",
    name: "Serve +1 pattern",
    category: "tactical",
    focus: ["serve", "tactics", "forehand"],
    kinds: ["tactical", "live"],
    minLevel: "intermediate",
    whatToDo:
      "Serve to a chosen target, then attack the likely reply with the next ball (e.g. serve wide, forehand into the open court).",
    howToDo: [
      "Decide the +1 before you serve.",
      "Recover to cover the highest-percentage reply.",
      "Attack the +1 only if the serve earns a short ball.",
    ],
    successCriteria: "Win 6 of 10 serve +1 patterns played out.",
    equipment: ["basket of balls", "target cones"],
    suitsGroup: false,
    baseIntensity: "high",
  },
  {
    id: "tc-return-plus-one",
    name: "Return +1 pattern",
    category: "tactical",
    focus: ["return", "tactics"],
    kinds: ["tactical", "live"],
    minLevel: "intermediate",
    whatToDo: "Return deep to a target, then take control of the next ball into the open court.",
    howToDo: [
      "Deep, safe return first — neutralise before you attack.",
      "Step in on the +1 if the return drew a weak reply.",
    ],
    successCriteria: "Neutralise or win 6 of 10 return +1 sequences.",
    equipment: ["basket of balls"],
    suitsGroup: false,
    baseIntensity: "high",
  },
  {
    id: "tc-cc-to-dtl",
    name: "Cross-court to down-the-line constraint",
    category: "tactical",
    focus: ["tactics", "forehand", "backhand"],
    kinds: ["tactical"],
    minLevel: "beginner",
    whatToDo:
      "Cooperative rally: both players must hit 3 cross-court balls before either is allowed to go down the line to open the point.",
    howToDo: [
      "Build the point patiently; earn the DTL ball.",
      "Change direction only on a ball inside the baseline.",
    ],
    successCriteria: "Reach 5 rallies where the DTL is hit off a genuinely short ball.",
    equipment: ["basket of balls"],
    suitsGroup: true,
    baseIntensity: "medium",
  },

  // ── Live-ball / competitive ────────────────────────────────────
  {
    id: "lv-tiebreak-constraint",
    name: "Constraint tiebreak to 7",
    category: "tactical",
    focus: ["tactics", "mental"],
    kinds: ["live"],
    minLevel: "beginner",
    whatToDo: "Play a tiebreak to 7 with a constraint (e.g. every point must start with a second serve, or first ball cross-court).",
    howToDo: [
      "Keep score out loud; treat it like a real match.",
      "Full between-point routine every point.",
    ],
    successCriteria: "Complete the tiebreak honouring the constraint on every point.",
    equipment: ["match balls"],
    suitsGroup: true,
    baseIntensity: "high",
  },
  {
    id: "lv-king-of-court",
    name: "King / Queen of the court",
    category: "tactical",
    focus: ["tactics", "movement", "mental"],
    kinds: ["live"],
    minLevel: "beginner",
    whatToDo: "Group game: challenger plays a point vs the 'king'; winner stays, loser rotates out. Coach feeds each point in.",
    howToDo: [
      "Play every point fully; no free points.",
      "Rotate quickly to keep work density high.",
    ],
    successCriteria: "Everyone plays at least 8 competitive points.",
    equipment: ["basket of balls"],
    suitsGroup: true,
    baseIntensity: "high",
  },
  {
    id: "lv-pressure-0-30",
    name: "Down 0–30 pressure game",
    category: "mental",
    focus: ["mental", "tactics", "serve"],
    kinds: ["live"],
    minLevel: "intermediate",
    whatToDo: "Every service game starts at 0–30 to the returner; server must problem-solve from behind.",
    howToDo: [
      "Trust the routine; play the next point, not the scoreboard.",
      "Serve to the body under pressure to reduce the returner's angle.",
    ],
    successCriteria: "Hold serve from 0–30 at least twice in the set.",
    equipment: ["match balls"],
    suitsGroup: false,
    baseIntensity: "high",
  },

  // ── Mental / routines ──────────────────────────────────────────
  {
    id: "mn-between-points",
    name: "Between-point routine",
    category: "mental",
    focus: ["mental"],
    kinds: ["technical", "cooldown"],
    minLevel: "beginner",
    whatToDo: "Rehearse a 4-stage between-point routine: react → recover (breathe, turn to the fence) → plan → play.",
    howToDo: [
      "Slow the breathing; relax the racquet hand.",
      "Decide the pattern before stepping up to the line.",
      "Same routine whether the last point was won or lost.",
    ],
    successCriteria: "Player runs the full routine on 10 consecutive points in the live block.",
    equipment: [],
    suitsGroup: true,
    baseIntensity: "low",
  },

  // ── Cool-down ──────────────────────────────────────────────────
  {
    id: "cd-stretch-review",
    name: "Static stretch & session review",
    category: "physical",
    focus: ["fitness"],
    kinds: ["cooldown"],
    minLevel: "beginner",
    whatToDo:
      "Static stretches (shoulders, hamstrings, hips, calves, forearms) held 20–30 s each, then a 2-minute review of what was worked and the next focus.",
    howToDo: [
      "Stretch to mild tension, never pain; breathe out into the stretch.",
      "Coach records what was worked and the single next-session priority.",
      "Rehydrate before leaving the court.",
    ],
    successCriteria: "Full stretch routine done and the session's next-step is written down.",
    equipment: ["water"],
    suitsGroup: true,
    baseIntensity: "low",
  },
];
