#!/usr/bin/env bash
# Prepare a fresh Ubuntu server and bring TennisAI up. Run ON THE SERVER:
#
#   git clone https://github.com/SOMAXOrlov/tennisai-central.git /opt/tennisai
#   cd /opt/tennisai && bash deploy/hetzner/setup.sh
#
# Safe to re-run: it never overwrites an existing .env, so secrets survive.
set -euo pipefail

cd "$(dirname "$0")"
HERE="$(pwd)"

say() { printf '\n\033[1m%s\033[0m\n' "$1"; }

if [ "$(id -u)" -ne 0 ]; then
  echo "Needs root: sudo bash deploy/hetzner/setup.sh"
  exit 1
fi

say "1/5 Docker"
if command -v docker >/dev/null 2>&1; then
  echo "already installed: $(docker --version)"
else
  apt-get update -qq
  apt-get install -y -qq docker.io docker-compose-v2
  systemctl enable --now docker
fi

say "2/5 Firewall"
# A web server needs 80 and 443 open. 80 is not optional even for an
# HTTPS-only site: Let's Encrypt validates over plain HTTP.
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
  ufw allow 80/tcp  >/dev/null
  ufw allow 443/tcp >/dev/null
  echo "ufw: 80 and 443 open"
else
  echo "ufw inactive — nothing to open here"
fi
echo "NOTE: if a Hetzner Cloud Firewall is attached to this server, 80 and 443"
echo "      must be allowed there TOO. The console shows it, this script cannot."

say "3/5 Configuration"
if [ -f .env ]; then
  echo ".env exists — leaving it alone"
else
  IP="$(curl -fsS --max-time 5 https://ipv4.icanhazip.com || true)"
  IP="${IP//[$'\r\n']/}"
  # sslip.io resolves any dashed IP in its domain back to that IP, which gives
  # Let's Encrypt a real hostname to certify. A certificate cannot be issued
  # for a bare IP address, and without one every password crosses in clear text.
  SITE="${IP//./-}.sslip.io"
  umask 077
  cat > .env <<ENVFILE
# Generated by setup.sh on first run. Secrets below are random and unique to
# this machine — losing this file logs everyone out (JWT_SECRET) and orphans
# the database (POSTGRES_PASSWORD). Back it up somewhere private.
SITE_ADDRESS=${SITE}
POSTGRES_PASSWORD=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)
JWT_SECRET=$(head -c 48 /dev/urandom | base64 | tr -d '/+=' | head -c 64)

# OFF until Gmail sending is configured. With it ON and no mail credentials,
# every new account is told to check an inbox that will never receive anything
# and can never log in.
REQUIRE_EMAIL_VERIFICATION=false
GMAIL_USER=
GMAIL_APP_PASSWORD=
MAIL_FROM_NAME=TennisAI

# Alternative to Gmail, for any SMTP provider (Resend, Brevo, Mailgun...).
# Gmail will not issue an app password until 2-Step Verification is on for the
# whole Google account; these credentials are handed over immediately.
# SMTP_HOST alone switches it on. MAIL_FROM must be an address the provider has
# authorised for your domain.
SMTP_HOST=
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASSWORD=
MAIL_FROM=

# Shared secret for the CI job that posts the ITF/ATP/WTA calendars in. The UTR
# calendar needs nothing — this server pulls it directly, every day.
FEED_PUSH_TOKEN=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 43)
FEED_REFRESH_HOUR_UTC=4

# Registration is open; this caps total accounts. Remove for no cap.
MAX_SIGNUPS=50

# Optional LLM features. Both must be set or they stay off and say so.
AI_PROVIDER=
AI_API_KEY=
ENVFILE
  echo "wrote $HERE/.env  (site: ${SITE})"
fi

say "4/5 Build and start"
docker compose up -d --build

say "5/5 Check"
sleep 8
docker compose ps
SITE_ADDRESS="$(grep -E '^SITE_ADDRESS=' .env | cut -d= -f2-)"
echo
echo "Health:"
curl -fsS "http://127.0.0.1/api/health" || echo "  (not answering yet — 'docker compose logs -f api')"
echo
echo
echo "Site: https://${SITE_ADDRESS}"
echo "The first HTTPS request can take ~30s while Caddy gets its certificate."
